### ISSUE TITLE
GitHub Streak Stats not working

### ISSUE THREAD

**Issue by max-programming** [arturssmirnovs/github-profile-readme-generator#36]
I tried to use GitHub Streak Stats on the site. Added by @DenverCoder1 at #35. But sadly, it was not working
![image](https://user-images.githubusercontent.com/51731966/97132808-043ed480-176e-11eb-9cf1-6a737acd3009.png)

**Comment by DenverCoder1** [comment]
It's working for me, make sure to enter a username in the Github Social field.

It may be helpful to make the Github username requirement more prominent so people won't miss it.

I made the mistake of skipping the social section a few times when trying to test it.

![image](https://user-images.githubusercontent.com/20955511/97133127-9be1fa00-1751-11eb-919d-83569429f6ca.png)

**Comment by DenverCoder1** [comment]
I now notice that it seems you do have the GitHub icon, so you must have entered a username. I'm not sure what was done differently because I was able to get it working (as shown above) on the live site. 🤔

**Comment by max-programming** [comment]
So. I tried entering the username first, and then enabling it. And it worked. But, maybe it wasn't working when I first enabled it and then entered the username. 
We should maybe disable those checkboxes until the username is entered

**Comment by arturssmirnovs** [comment]
Looks like it's working fine.. 
Just i noticed that if you tick checkbox first and they type username, it sends multiple requests to stats servers..
And in developer console it's showing PANDING for few seconds (around 10) while it finish all previous requests and loads last one..
I guess that could be confusing.. 
Yeah, I will make disabled inputs while username is not entered and will make another input in stats tab just for GitHub username..

That should solve it.. But it's working fine, so no worries!

@DenverCoder1 Good job on this one, looks cool feature! :)

**Comment by pandyaved98** [comment]
M GitHub streaks stats aren't updating. I've created a new repo and committed some files in it but it's still showing the same as before no increment in numbers. And it's my 3rd day in a row for contributions but it's still showing 2 in place of 3.

**Comment by DenverCoder1** [comment]
@pandyaved98 It does say 3 on your profile when I look at it. The streak stats do not update instantly because the image may be cached by GitHub and also the data from GitHub might not be visible until a few hours after. There can be short delays that aren't avoidable, but it will never be more than a day behind.

**Comment by sudiptapradhan** [comment]
I've a doubt.
I need my github stats and streak to be side by side each other... But they are coming one below the other... What can I do?

**Comment by SilverC0de** [comment]
It is possible that the image is being cached by github. You should check your profile from another browser/device or use incognito mode
